name: Build Containers
on:
  pull_request:
    branches:
      - master
jobs:
  build-containers:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build worker container
        uses: docker/build-push-action@v2
        with:
          file: deploy/worker-kinetic-no-gpu.docker
          context: .
          push: false
          tags: amzracing/rbb-tools:latest
      - name: Build API container
        uses: docker/build-push-action@v2
        with:
          file: deploy/api-server.docker
          context: .
          push: false
          tags: amzracing/rbb-tools:latest

      - name: Build GPU worker container
        uses: docker/build-push-action@v2
        with:
          file: deploy/worker-kinetic-gpu.docker
          context: .
          push: false
          tags: amzracing/rbb-tools-gpu-nvidia:latest
